/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AnnualInspectionRouteImport } from './routes/annual-inspection'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({ id: '/areas', path: '/areas', getParentRoute: () => rootRouteImport } as any)
const CareersRoute = CareersRouteImport.update({ id: '/careers', path: '/careers', getParentRoute: () => rootRouteImport } as any)
const FleetRoute = FleetRouteImport.update({ id: '/fleet', path: '/fleet', getParentRoute: () => rootRouteImport } as any)
const ResourcesRoute = ResourcesRouteImport.update({ id: '/resources', path: '/resources', getParentRoute: () => rootRouteImport } as any)
const ReviewsRoute = ReviewsRouteImport.update({ id: '/reviews', path: '/reviews', getParentRoute: () => rootRouteImport } as any)
const WorkRoute = WorkRouteImport.update({ id: '/work', path: '/work', getParentRoute: () => rootRouteImport } as any)
const AnnualInspectionRoute = AnnualInspectionRouteImport.update({ id: '/annual-inspection', path: '/annual-inspection', getParentRoute: () => rootRouteImport } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({ id: '/privacy-policy', path: '/privacy-policy', getParentRoute: () => rootRouteImport } as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({ id: '/terms-conditions', path: '/terms-conditions', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/areas': typeof AreasRoute
  '/careers': typeof CareersRoute
  '/fleet': typeof FleetRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/work': typeof WorkRoute
  '/annual-inspection': typeof AnnualInspectionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/areas': typeof AreasRoute
  '/careers': typeof CareersRoute
  '/fleet': typeof FleetRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/work': typeof WorkRoute
  '/annual-inspection': typeof AnnualInspectionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/areas': typeof AreasRoute
  '/careers': typeof CareersRoute
  '/fleet': typeof FleetRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/work': typeof WorkRoute
  '/annual-inspection': typeof AnnualInspectionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/services' | '/areas' | '/careers' | '/fleet' | '/resources' | '/reviews' | '/work' | '/annual-inspection' | '/privacy-policy' | '/terms-conditions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/services' | '/areas' | '/careers' | '/fleet' | '/resources' | '/reviews' | '/work' | '/annual-inspection' | '/privacy-policy' | '/terms-conditions'
  id: '__root__' | '/' | '/contact' | '/services' | '/areas' | '/careers' | '/fleet' | '/resources' | '/reviews' | '/work' | '/annual-inspection' | '/privacy-policy' | '/terms-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  AreasRoute: typeof AreasRoute
  CareersRoute: typeof CareersRoute
  FleetRoute: typeof FleetRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  WorkRoute: typeof WorkRoute
  AnnualInspectionRoute: typeof AnnualInspectionRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': { id: '/areas'; path: '/areas'; fullPath: '/areas'; preLoaderRoute: typeof AreasRouteImport; parentRoute: typeof rootRouteImport }
    '/careers': { id: '/careers'; path: '/careers'; fullPath: '/careers'; preLoaderRoute: typeof CareersRouteImport; parentRoute: typeof rootRouteImport }
    '/fleet': { id: '/fleet'; path: '/fleet'; fullPath: '/fleet'; preLoaderRoute: typeof FleetRouteImport; parentRoute: typeof rootRouteImport }
    '/resources': { id: '/resources'; path: '/resources'; fullPath: '/resources'; preLoaderRoute: typeof ResourcesRouteImport; parentRoute: typeof rootRouteImport }
    '/reviews': { id: '/reviews'; path: '/reviews'; fullPath: '/reviews'; preLoaderRoute: typeof ReviewsRouteImport; parentRoute: typeof rootRouteImport }
    '/work': { id: '/work'; path: '/work'; fullPath: '/work'; preLoaderRoute: typeof WorkRouteImport; parentRoute: typeof rootRouteImport }
    '/annual-inspection': { id: '/annual-inspection'; path: '/annual-inspection'; fullPath: '/annual-inspection'; preLoaderRoute: typeof AnnualInspectionRouteImport; parentRoute: typeof rootRouteImport }
    '/privacy-policy': { id: '/privacy-policy'; path: '/privacy-policy'; fullPath: '/privacy-policy'; preLoaderRoute: typeof PrivacyPolicyRouteImport; parentRoute: typeof rootRouteImport }
    '/terms-conditions': { id: '/terms-conditions'; path: '/terms-conditions'; fullPath: '/terms-conditions'; preLoaderRoute: typeof TermsConditionsRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  AreasRoute: AreasRoute,
  CareersRoute: CareersRoute,
  FleetRoute: FleetRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  WorkRoute: WorkRoute,
  AnnualInspectionRoute: AnnualInspectionRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
